---
# make sure homebrew is installed, update brew and install applications

#- name: application installs
#  include: homebrew.yml

#- name: getting downloads
#  get_url:
#    url: "{{item.value.url}}"
#    dest: "{{item.value.dest}}"
#  with_dict: "{{downloads}}"


# Install ubuntu deb files
- name: install deb applications
  include: "filename.yml deb={{item.deb}} name={{item.name}} dest={{item.dest}}"
  with_dict: "{{ debs }}"
  loop_control:
    label: "{{ item.name }}"

# Install OS X apps
- name: install homebrew applications
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{brew_applications}}"

- name: install homebrew cask applications
  homebrew_cask:
    name: "{{item}}"
    state: installed
  become: true
#  ignore_errors: true
  with_items: "{{cask_applications}}"
