---
# doing configuration

- name: install ssh config
  copy:
    src: ssh-config
    dest: ~/.ssh/config
    mode: 0600

#- name: getting dracula theme for oh-my-zsh
#  git:
#    repo: https://github.com/dracula/zsh.git
#    dest: "{{general.local_home}}/.oh-my-zsh_dracula_theme"

#- name: sym linking oh-my-zsh theme
#  file:
#    src: "{{general.local_home}}/.oh-my-zsh_dracula_theme/dracula.zsh-theme"
#    dest: "{{general.local_home}}/.oh-my-zsh/themes/dracula.zsh-theme"
#    state: link






