---
# install editors

- block:
  - name: install Sublime repo signing key
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: add Sublime repo
    apt_repository:
      repo: deb https://download.sublimetext.com/ apt/stable/
      state: present

  - name: install Sublime from the repo
    apt:
      package: sublime-text
      state: present
  when: ansible_distribution == 'Ubuntu'
  become: true

#- name: "install Sublime Text 3"
#  script:
#    src: roles/setup/files/install-sublime.sh
#    creates: /usr/bin/subl

- name: create Sublime config folders
  file:
    path: "{{ general.sublime_local }}/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - Local
    - Packages/User
    - Installed Packages/

# Deprecated: the license file is unique per machine
#- name: install Sublime Text license
#  copy:
#    src: License.sublime_license
#    dest: "{{ general.sublime_local }}/Local/License.sublime_license"

- name: install Sublime Text user settings
  copy:
    src: Preferences.sublime-settings
    dest: "{{ general.sublime_local }}/Packages/User/Preferences.sublime-settings"

- name: install Package Control
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: "{{ general.sublime_local }}/Installed Packages/Package Control.sublime-package"

- name: install Package settings
  copy:
    src: "{{ item }}"
    dest: "{{ general.sublime_local }}/Packages/User/"
    force: no
  with_items:
    - Package Control.sublime-settings
    - trailing_spaces.sublime-settings
    - ApplySyntax.sublime-settings

- name: install ansible-lint
  become: true
  pip:
    name: ansible-lint

- name: create dotfile directories
  file:
    path: "{{ general.local_home }}/{{ item }}"
    state: directory
  with_items:
    - ".fonts"
    - ".vim/autoload"
    - .vim/colors

- name: install Anonymous Pro
  unarchive:
      src: http://www.marksimonson.com/assets/content/fonts/AnonymousPro-1.002.zip
      dest: "{{ general.fonts }}"
      remote_src: true
  ignore_errors: true

- name: setting up vim-plug
  get_url:
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    dest: "{{general.local_home}}/.vim/autoload/plug.vim"

- name: install vim-monokai
  get_url:
    url: 'https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim'
    dest: "{{ general.local_home }}/.vim/colors/monokai.vim"

- name: install vimrc
  copy:
    src: vimrc
    dest: "{{ general.local_home }}/.vimrc"
