---
# install editors

#- name: "install Sublime Text 3"
#  script:
#    src: roles/setup/files/install-sublime.sh
#    creates: /usr/bin/subl
- name: determine if Sublime Text is Installed
  stat:
    path: /usr/bin/subl
  register: sublimetext

- name: Install Sublime Text 3 
  become: true
  apt:
    deb: https://download.sublimetext.com/sublime-text_build-3126_amd64.deb
  when: sublimetext.stat.exists == false

- name: create Sublime config folders
  file:
    path: "{{ general.local_home }}/.config/sublime-text-3/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - Local
    - Packages/User
    - Installed Packages/

- name: install Sublime Text license
  copy:
    src: License.sublime_license
    dest: "{{ general.local_home}}/.config/sublime-text-3/Local/License.sublime_license"

- name: install Sublime Text user settings
  copy:
    src: Preferences.sublime-settings
    dest: "{{ general.local_home }}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"

- name: install Package Control
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: "{{ general.local_home }}/.config/sublime-text-3/Installed Packages/Package Control.sublime-package"

- name: install Package Control settings
  copy:
    src: Package Control.sublime-settings
    dest: "{{ general.local_home }}/.config/sublime-text-3/Packages/User/Package Control.sublime-settings"
    force: no

- name: install ansible-lint
  become: true
  pip:
    name: ansible-lint

- name: create dotfile directories
  file:
    path: "{{ general.local_home }}/{{ item }}"
    state: directory
  with_items:
    - ".fonts"
    - ".vim/autoload"
    - .vim/colors

- name: install Anonymous Pro
  unarchive:
      src: http://www.marksimonson.com/assets/content/fonts/AnonymousPro-1.002.zip
      dest: "{{ general.local_home }}/.fonts"
      remote_src: true
  ignore_errors: true

- name: setting up vim-plug
  get_url:
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    dest: "{{general.local_home}}/.vim/autoload/plug.vim"
  
- name: install vim-monokai
  get_url:
    url: 'https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim'
    dest: "{{ general.local_home }}/.vim/colors/monokai.vim"

- name: install vimrc
  copy:
    src: vimrc
    dest: "{{ general.local_home }}/.vimrc"
